<?php
/**
 * @file rtpr_line_item.module
 * Demonstrates the addition of a new line item type programatically
 *
 */


/**
 * Implements hook_commerce_line_item_type_info().
 *
 * - example_line_item_1 is simply a clone of the 'product' line item type. It's
 *   a simple way to get a differentiated line item type.
 * - signature_confirmation is completely implemented and is not a product line
 *   item type but rather a "surcharge", and the hook_commerce_order_presave()
 *   is provided to make sure that there is one for every order.
 *
 * @see hook_commerce_line_item_type_info().
 * @see http://www.drupalcommerce.org/specification/info-hooks/checkout
 *
 */
function rtpr_line_item_commerce_line_item_type_info() {

  $line_item_types['signature_confirmation'] = array(
    'name' => t('Signature Confirmation'),
    'description' => t('Signature Confirmation'),
    'product' => FALSE,

    // Here you can change the text in the submit button in the order admin
    // line item add area.
    'add_form_submit_value' => t('Add Signature Confirmation'),

    // We could use 'base' to configure the forms we need but instead we'll
    // name the callbacks explicitly.

    // 'base' => 'rtpr_line_item_example_2',

    'callbacks' => array(
      'configuration' => 'rtpr_line_item_signature_confirmation_configuration',
      'title' => 'rtpr_line_item_signature_confirmation_title',
      'add_form' => 'rtpr_line_item_signature_confirmation_add_form',
      'add_form_submit' => 'rtpr_line_item_signature_confirmation_add_form_submit',
    ),
  );

  return $line_item_types;
}


/**
 * Configure the line item with additional fields or whatever.
 *
 * This function is called by the line item module when it is enabled or this
 * module is enabled. It invokes this function using the configuration_callback
 * as specified above. Other modules defining product line item types should
 * use this function to ensure their types have the required fields.
 *
 * @param $line_item_type
 *   The info array of the line item type being configured.
 *
 * @see commerce_product_line_item_configuration()
 */
function rtpr_line_item_signature_confirmation_configuration($line_item_type) {
  $type = $line_item_type['type'];

  // Here we could add fields or other configuration.

}

/**
 * Returns a title for this line item.
 */
function rtpr_line_item_signature_confirmation_title($line_item) {
  return(t('Signature Confirmation'));
}

/**
 * Returns the elements necessary to add a product line item through a line item
 * manager widget (on the order form).
 */
function rtpr_line_item_signature_confirmation_add_form($element, &$form_state) {
  $form = array();

  return $form;
}

/**
 * Adds the selected product information to a line item added via a line item
 *   manager widget (on the admin order page).
 *
 * @param $line_item
 *   The newly created line item object.
 * @param $element
 *   The array representing the widget form element.
 * @param $form_state
 *   The present state of the form upon the latest submission.
 * @param $form
 *   The actual form array.
 *
 * @return
 *   NULL if all is well or an error message if something goes wrong.
 */
function rtpr_line_item_signature_confirmation_add_form_submit(&$line_item, $element, &$form_state, $form) {
  $line_item->line_item_label = t('Signature Confirmation');

  // Wrap the line item and product to easily set field information.
  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

  // Provide a default price.
  $amount = variable_get('rtpr_line_item_signature_confirmation_amount', 200);
  $currency_code = variable_get('rtpr_line_item_signature_confirmation_currency', 'USD');

  $line_item->commerce_unit_price = array('und' => array(
    '0' => array('amount' => $amount, 'currency_code' => $currency_code)
  ));

  if (!is_null($line_item_wrapper->commerce_unit_price->value())) {
    // Add the base price to the components array.
    if (!commerce_price_component_load($line_item_wrapper->commerce_unit_price->value(), 'confirmation')) {
      $line_item_wrapper->commerce_unit_price->data = commerce_price_component_add(
        $line_item_wrapper->commerce_unit_price->value(),
        'confirmation',
        $line_item_wrapper->commerce_unit_price->value(),
         TRUE,
         FALSE
      );
    }
  }

}


/**
 * Utility function which creates a new example_2 line item populated with the
 * a price of $5.00, etc..
 *
 * @param $order_id
 *   The ID of the order the line item belongs to (if available).
 *
 * @return
 *   The fully loaded line item..
 */
function rtpr_line_item_signature_confirmation_new($order_id = 0) {
  $type = 'signature_confirmation';

  // Create the new line item.
  $line_item = entity_create('commerce_line_item', array(
    'type' => $type,
    'order_id' => $order_id,
    'quantity' => 1,
  ));

  // For this example, we'll use a price of USD $5.00 for the "surcharge".
  $amount = variable_get('rtpr_line_item_signature_confirmation_amount', 200);
  $currency_code = variable_get('rtpr_line_item_signature_confirmation_currency', 'USD');
  $line_item->line_item_label = t('Signature Confirmation');
  $line_item->commerce_unit_price = array('und' => array(
    '0' => array('amount' => $amount, 'currency_code' => $currency_code)
  ));

  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

  if (!is_null($line_item_wrapper->commerce_unit_price->value())) {
    // Add the base price to the components array.
    if (!commerce_price_component_load($line_item_wrapper->commerce_unit_price->value(), 'confirmation')) {
      $component = commerce_price_component_add(
        $line_item_wrapper->commerce_unit_price->value(),
        'confirmation',
        $line_item_wrapper->commerce_unit_price->value(),
         TRUE,
      FALSE
      );
     // unset($component['components'][0]);
      $line_item_wrapper->commerce_unit_price->data =  $component;
    }
  }
  // Return the line item.
  return $line_item;
}

// There should be one of our example line items on every order, so make sure
// it's there or add it.
function rtpr_line_item_commerce_order_presave($order) {
  // Find out if our order already has an example_2 line item.
  $type_exists = FALSE;

  $wrapper = entity_metadata_wrapper('commerce_order', $order);

  if (!empty($order->commerce_line_items['und'])) {
    foreach($order->commerce_line_items['und'] as $delta => $line_item_entry) {
      if ($line_item = commerce_line_item_load($line_item_entry['line_item_id'])) {
       if ($line_item->type == 'signature_confirmation') {
          if($wrapper->field_signature_confirmation->value()) {
            $type_exists = TRUE;
            break;
          } else {
            unset($order->commerce_line_items['und'][$delta]);
            break;
          }
          
        }
      }
    }
  }

  // If our line item is not yet in the order and the order has an ID,
  // create a line item to add to the order.
  if (!$type_exists && $order->order_id > 0 && $wrapper->field_signature_confirmation->value()) {
    $line_item = rtpr_line_item_signature_confirmation_new($order->order_id);
    commerce_line_item_save($line_item);
    $order->commerce_line_items['und'][] = array('line_item_id' => $line_item->line_item_id);
  }
  

}


/**
 * Implements hook_commerce_price_component_type_info().
 */
function rtpr_line_item_commerce_price_component_type_info() {
  $components = array();

  // Define a generic shipping price component type.
  $components['confirmation'] = array(
    'title' => t('Confirmation'),
    'weight' => 100,
    'display_title' => t('Signature Confirmation'), 
  );

 

  return $components;
}


function rtpr_line_item_form_commerce_checkout_form_shipping_alter(&$form, $form_state) {

  $form['commerce_fieldgroup_pane__group_signature_confirmation']['field_signature_confirmation']['und']['#title'] = $form['commerce_fieldgroup_pane__group_signature_confirmation']['field_signature_confirmation']['und']['#description'];
  
  $form['commerce_fieldgroup_pane__group_signature_confirmation']['field_signature_confirmation']['#prefix'] = '<div><br/><b>Signature Confirmation</b>';
  
  $form['commerce_fieldgroup_pane__group_signature_confirmation']['field_signature_confirmation']['#suffix'] = '</div>';
  
  $form['commerce_fieldgroup_pane__group_signature_confirmation']['field_signature_confirmation']['und']['#description']= "";
}